version: '2'
services:
  app:
    image: node:6.9-alpine
    container_name: app
    hostname: node_express
    volumes:
      - "./node/app:/src"
    working_dir: /src
    command: [sh, -c, npm install && npm start]
    ports:
      - "3000:3000"
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql57
    hostname: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --explicit_defaults_for_timestamp=true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=application_db"
      - "MYSQL_USER=matatsuna"
      - "MYSQL_PASSWORD=matatsuna"